### ISSUE TITLE
docker: Stop relying on Docker. Do not build any Docker images

### ISSUE THREAD

**Issue by stephen-fox** [equinixmetal-buildkite/trivy-buildkite-plugin#9]
The plugin currently relies on Docker for two reasons:

- To run trivy itself (by volume mounting the cloned git repo into the trivy container)
- To build the user's Dockerfile at the root of the repo

We cannot assume that Docker will be available in the CI environment. This is especially true if the plugin is already running in a container / is a child of an isolated process. We should stop using Docker altogether in this plugin. Any image scanning features could go into the docker-build plugin: https://github.com/equinixmetal-buildkite/docker-build-buildkite-plugin

We should investigate using `go install github.com/aquasecurity/trivy/cmd/trivy@latest` (or `@vX.Y.Z`). This will likely require an upstream change, as something about their project breaks `go install ...`:

```
$ go install github.com/aquasecurity/trivy/cmd/trivy@latest
go: downloading github.com/aquasecurity/trivy v0.31.3
go: github.com/aquasecurity/trivy/cmd/trivy@latest (in github.com/aquasecurity/trivy@v0.31.3):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by JAORMX** [comment]
This has already been addressed.
